### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by wahoonie76** [Gratt-5r2/zCleanupCamSpace#1]
Hi Gratt,

I saw your good-sounding plugin on [worldofplayers.ru](https://worldofplayers.ru/threads/42522/) and tried to use it both on Gothic 1 and Gothic 2 The night of the  raven. The games didn't want to start and errors occurs (see screenshots). I tried it with other union-plugins also "standalone".

Greetings

wahoonie

![zCleanupCamSpace-G1-Error](https://user-images.githubusercontent.com/20705724/139555476-48e7dba9-2bd7-494d-913b-e52266d3d54d.jpg)
![zCleanupCamSpace-G2-Error](https://user-images.githubusercontent.com/20705724/139555477-2af0ac57-ce42-480d-958f-92e1d38fbe00.jpg)

**Comment by Gratt-5r2** [comment]
> Hi Gratt,
> 
> I saw your good-sounding plugin on [worldofplayers.ru](https://worldofplayers.ru/threads/42522/) and tried to use it both on Gothic 1 and Gothic 2 The night of the raven. The games didn't want to start and errors occurs (see screenshots). I tried it with other union-plugins also "standalone".

Hi! Thanks for the report!
Please install Union 1.0l and try again.
Best wishes!

**Comment by wahoonie76** [comment]
> Please install Union 1.0l and try again.

Hi again,
At this time I tried the new plugin union 1.0l wasn't available in ressource manager. Now it is and your plugin works for me in Gothic 2 The night of the raven, but only if I disable the D3D11-renderer.
Thanks & Greets!
wahoonie

**Comment by Gratt-5r2** [comment]
Nice to know!
Unfortunately, dx11 cannot work with the vob transparency. I hope that will be added in the future.
I was glad to help.
